namespace MouseDisaster
{
    public static partial class MouseDisasterTraitCatalog
    {
        private static readonly MouseDisasterTraitDefinition[] Definitions = new MouseDisasterTraitDefinition[]
        {
            new MouseDisasterTraitDefinition(
                "T01", "MouseDisaster_Trait_HardyLabor",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.72f,
                new[] { "A001", "A002", "A005", "A068", "Y030", "Y031" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T02", "MouseDisaster_Trait_FamineFarmer",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.7f,
                new[] { "A001", "A002", "A003", "A068", "Y031" },
                new[] { "O-011", "N-030", "N-044" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T03", "MouseDisaster_Trait_FieldGleaner",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.68f,
                new[] { "A003", "A016", "Y001", "Y018" },
                new[] { "O-008", "O-010" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T04", "MouseDisaster_Trait_DisasterHerder",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.66f,
                new[] { "A004", "Y007", "Y032", "Y045" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T05", "MouseDisaster_Trait_WellBearer",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.64f,
                new[] { "A005", "Y033", "Y021" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T06", "MouseDisaster_Trait_MoldSifter",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.62f,
                new[] { "A007", "A029", "Y035" },
                new[] { "N-011", "N-012" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T07", "MouseDisaster_Trait_GranaryCarpenter",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.64f,
                new[] { "A009", "A024", "Y036", "Y042" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T08", "MouseDisaster_Trait_RagTailor",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.6f,
                new[] { "A010", "Y037" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T09", "MouseDisaster_Trait_HerbReader",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.66f,
                new[] { "A012", "A030", "A060", "Y039" },
                new[] { "N-013" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T10", "MouseDisaster_Trait_NightFugitive",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.63f,
                new[] { "A014", "A017", "Y006", "Y018" },
                new[] { "O-008", "O-009" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T11", "MouseDisaster_Trait_SnowGuide",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.58f,
                new[] { "A017", "Y044" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T12", "MouseDisaster_Trait_DustBearer",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Mixed, 0.58f,
                new[] { "A018", "Y045" },
                new[] { "O-012" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T13", "MouseDisaster_Trait_CampWatcher",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.6f,
                new[] { "A019", "Y012", "Y046" },
                new[] { "O-014", "N-026" },
                MouseDisasterPawnHistoryEventCategory.Siege),
            new MouseDisasterTraitDefinition(
                "T14", "MouseDisaster_Trait_AlmsSpeaker",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.7f,
                new[] { "A026", "A052", "A058", "Y016" },
                new[] { "O-004", "O-005", "O-011", "N-027", "N-038" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T15", "MouseDisaster_Trait_JunkAppraiser",
                MouseDisasterTraitSlot.Adult, MouseDisasterTraitPolarity.Positive, 0.62f,
                new[] { "A035", "A057", "A061" },
                new[] { "O-012", "O-013", "N-014" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T16", "MouseDisaster_Trait_GrainMediator",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.6f,
                new[] { "A036", "A055", "Y016", "Y022" },
                new[] { "N-011", "N-012", "O-001" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T17", "MouseDisaster_Trait_WoundTender",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.64f,
                new[] { "A030", "A046", "A060", "Y028" },
                new[] { "N-013" },
                MouseDisasterPawnHistoryEventCategory.Plague),
            new MouseDisasterTraitDefinition(
                "T18", "MouseDisaster_Trait_EggKeeper",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.68f,
                new[] { "A031", "A050", "A051", "Y005", "Y014", "Y015" },
                new[] { "O-002", "O-003", "O-013", "N-015" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T19", "MouseDisaster_Trait_LeanHunger",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.66f,
                new[] { "A014", "A054", "A068", "Y018" },
                new[] { "N-030", "N-044" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T20", "MouseDisaster_Trait_ThickFur",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.55f,
                new[] { "A017", "Y044" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T21", "MouseDisaster_Trait_FinePaws",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.56f,
                new[] { "A010", "A008", "Y037", "Y008" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T22", "MouseDisaster_Trait_PathScout",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.64f,
                new[] { "A021", "A023", "A074", "Y006", "Y023" },
                new[] { "N-016", "N-019", "N-022" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T23", "MouseDisaster_Trait_ColumnLead",
                MouseDisasterTraitSlot.Adult, MouseDisasterTraitPolarity.Positive, 0.6f,
                new[] { "A023", "A074", "A055" },
                new[] { "O-001", "N-027" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T24", "MouseDisaster_Trait_ReliefCook",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.62f,
                new[] { "A007", "A029", "A059", "Y035" },
                new[] { "N-011", "N-012", "O-011" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T25", "MouseDisaster_Trait_FamineHunter",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Positive, 0.58f,
                new[] { "A042", "Y038" },
                new[] { "O-008", "O-010" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T26", "MouseDisaster_Trait_HungerRage",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.7f,
                new[] { "A041", "A049", "A038" },
                new[] { "N-030", "N-044" },
                MouseDisasterPawnHistoryEventCategory.Theft),
            new MouseDisasterTraitDefinition(
                "T27", "MouseDisaster_Trait_FoodSnatcher",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.72f,
                new[] { "A041", "A053", "Y017" },
                new[] { "O-006", "O-007", "N-031", "N-039" },
                MouseDisasterPawnHistoryEventCategory.Theft),
            new MouseDisasterTraitDefinition(
                "T28", "MouseDisaster_Trait_PlagueDread",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.74f,
                new[] { "A044", "A045", "A070", "Y010", "Y028" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.Plague),
            new MouseDisasterTraitDefinition(
                "T29", "MouseDisaster_Trait_NightTerrors",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.6f,
                new[] { "A019", "Y012", "Y046", "Y041" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T30", "MouseDisaster_Trait_FamineSloth",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.58f,
                new[] { "A006", "A032", "Y009", "Y041" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T31", "MouseDisaster_Trait_GrainGreed",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.64f,
                new[] { "A037", "A038", "Y034" },
                new[] { "O-012" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T32", "MouseDisaster_Trait_Distrustful",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.6f,
                new[] { "A020", "A067", "Y026" },
                new[] { "N-029", "N-043" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T33", "MouseDisaster_Trait_WeakFlesh",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.58f,
                new[] { "A011", "A044", "A046" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.Plague),
            new MouseDisasterTraitDefinition(
                "T34", "MouseDisaster_Trait_WeakGut",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.56f,
                new[] { "A007", "A044", "Y004" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.Plague),
            new MouseDisasterTraitDefinition(
                "T35", "MouseDisaster_Trait_Chillblood",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.52f,
                new[] { "A017", "Y044", "Y018" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T36", "MouseDisaster_Trait_FamineGloom",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Negative, 0.62f,
                new[] { "A020", "A022", "Y011", "Y041" },
                new[] { "O-003", "N-030" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T37", "MouseDisaster_Trait_WailingYoung",
                MouseDisasterTraitSlot.Young, MouseDisasterTraitPolarity.Negative, 0.7f,
                new[] { "Y001", "Y011", "Y013", "Y015", "Y041" },
                new[] { "O-002", "O-009", "N-029" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T38", "MouseDisaster_Trait_BitingYoung",
                MouseDisasterTraitSlot.Young, MouseDisasterTraitPolarity.Negative, 0.68f,
                new[] { "Y017", "Y043", "Y019" },
                new[] { "O-007", "N-039" },
                MouseDisasterPawnHistoryEventCategory.Theft),
            new MouseDisasterTraitDefinition(
                "T39", "MouseDisaster_Trait_AlmsHate",
                MouseDisasterTraitSlot.Adult, MouseDisasterTraitPolarity.Negative, 0.58f,
                new[] { "A026", "A058", "A039" },
                new[] { "O-004", "O-005", "O-014" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T40", "MouseDisaster_Trait_GrudgeKeeper",
                MouseDisasterTraitSlot.Adult, MouseDisasterTraitPolarity.Negative, 0.6f,
                new[] { "A039", "A040", "A048" },
                new[] { "O-014", "N-026", "N-031" },
                MouseDisasterPawnHistoryEventCategory.Conflict),
            new MouseDisasterTraitDefinition(
                "T41", "MouseDisaster_Trait_PlagueSurvivor",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Mixed, 0.66f,
                new[] { "A046", "A070", "Y028" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.Plague),
            new MouseDisasterTraitDefinition(
                "T42", "MouseDisaster_Trait_GrainSneak",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Mixed, 0.64f,
                new[] { "A047", "A041", "Y017" },
                new[] { "O-006", "O-007" },
                MouseDisasterPawnHistoryEventCategory.Theft),
            new MouseDisasterTraitDefinition(
                "T43", "MouseDisaster_Trait_SiegeDigger",
                MouseDisasterTraitSlot.Adult, MouseDisasterTraitPolarity.Mixed, 0.62f,
                new[] { "A048", "A072", "A015" },
                new[] { "O-014", "N-026", "N-041" },
                MouseDisasterPawnHistoryEventCategory.Siege),
            new MouseDisasterTraitDefinition(
                "T44", "MouseDisaster_Trait_GranaryBreaker",
                MouseDisasterTraitSlot.Adult, MouseDisasterTraitPolarity.Mixed, 0.6f,
                new[] { "A049", "A038" },
                new[] { "N-030", "N-044" },
                MouseDisasterPawnHistoryEventCategory.Conflict),
            new MouseDisasterTraitDefinition(
                "T45", "MouseDisaster_Trait_AilingMother",
                MouseDisasterTraitSlot.Adult, MouseDisasterTraitPolarity.Mixed, 0.7f,
                new[] { "A051", "A052", "A065" },
                new[] { "O-003", "N-025", "N-040" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T46", "MouseDisaster_Trait_FamilyThief",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Mixed, 0.66f,
                new[] { "A053", "Y017" },
                new[] { "O-006", "O-007", "N-039" },
                MouseDisasterPawnHistoryEventCategory.Theft),
            new MouseDisasterTraitDefinition(
                "T47", "MouseDisaster_Trait_QuarantineGuard",
                MouseDisasterTraitSlot.Adult, MouseDisasterTraitPolarity.Mixed, 0.6f,
                new[] { "A045", "A071" },
                new string[0],
                MouseDisasterPawnHistoryEventCategory.Plague),
            new MouseDisasterTraitDefinition(
                "T48", "MouseDisaster_Trait_WrongKin",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Mixed, 0.58f,
                new[] { "A067", "Y026" },
                new[] { "N-029", "N-043", "N-028", "N-042" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T49", "MouseDisaster_Trait_CrowdChild",
                MouseDisasterTraitSlot.Young, MouseDisasterTraitPolarity.Mixed, 0.62f,
                new[] { "Y013", "Y025", "Y027" },
                new[] { "O-001", "N-028" },
                MouseDisasterPawnHistoryEventCategory.None),
            new MouseDisasterTraitDefinition(
                "T50", "MouseDisaster_Trait_WildHole",
                MouseDisasterTraitSlot.Any, MouseDisasterTraitPolarity.Mixed, 0.64f,
                new[] { "A054", "Y018", "Y001" },
                new[] { "O-008", "O-009", "O-010" },
                MouseDisasterPawnHistoryEventCategory.None),
        };
    }
}
