using System.Collections.Generic;
using RimWorld;
using Verse;

namespace MouseDisaster
{
    public static partial class MouseDisasterPawnHistoryCatalog
    {
        private static readonly List<MouseDisasterPawnHistoryDefinition> Definitions = new List<MouseDisasterPawnHistoryDefinition>
        {
            new MouseDisasterPawnHistoryDefinition(
                "A001", "MouseDisaster_History_A001", "鼠灾 佃户逃难",
                MouseDisasterPawnHistorySlot.Adult, 0.2f,
                18f, true, float.PositiveInfinity, false,
                0f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "种植必定单火, 有可能双火(也就是兴趣度), 种植技能必定在10~15之间",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 10, 15) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Plants", 1f, 0.35f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A002", "MouseDisaster_History_A002", "鼠灾 旱田守望",
                MouseDisasterPawnHistorySlot.Adult, 0.12f,
                18f, true, float.PositiveInfinity, false,
                5f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "种植必定单火, 有可能双火; 种植技能在6~12之间; 不强制增加特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 6, 12) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Plants", 1f, 0.35f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A003", "MouseDisaster_History_A003", "鼠灾 废田拾穗",
                MouseDisasterPawnHistorySlot.Adult, 0.14f,
                18f, true, float.PositiveInfinity, false,
                -10f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "种植技能在3~9之间; 动物技能在1~4之间; 更适合低装备生成",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 3, 9), new MouseDisasterPawnHistorySkillRange("Animals", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A004", "MouseDisaster_History_A004", "鼠灾 灾年牧鼠",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, float.PositiveInfinity, false,
                -15f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "动物必定单火, 有可能双火; 动物技能在6~12之间; 可优先选择照料类特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Animals", 6, 12) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Animals", 1f, 0.35f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A005", "MouseDisaster_History_A005", "鼠灾 旱井挑水",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, 55f, false,
                -5f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "", "", "种植技能在2~6之间; 建造技能在2~5之间; 移动和搬运能力不应被严重削弱",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 2, 6), new MouseDisasterPawnHistorySkillRange("Construction", 2, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A006", "MouseDisaster_History_A006", "鼠灾 谷仓旧账",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 60f, false,
                -20f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "智识技能在5~10之间; 社交技能在2~6之间; 不要求战斗兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 5, 10), new MouseDisasterPawnHistorySkillRange("Social", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A007", "MouseDisaster_History_A007", "鼠灾 霉粮筛手",
                MouseDisasterPawnHistorySlot.Adult, 0.11f,
                18f, true, 60f, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "烹饪技能在4~9之间; 种植技能在2~5之间; 烹饪必定单火",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Cooking", 4, 9), new MouseDisasterPawnHistorySkillRange("Plants", 2, 5) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Cooking", 1f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A008", "MouseDisaster_History_A008", "鼠灾 石磨孤徒",
                MouseDisasterPawnHistorySlot.Adult, 0.12f,
                18f, true, 30f, false,
                -15f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <30", "", "", "制作技能在3~8之间; 烹饪技能在1~4之间; 可能有制作兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Crafting", 3, 8), new MouseDisasterPawnHistorySkillRange("Cooking", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A009", "MouseDisaster_History_A009", "鼠灾 修仓木匠",
                MouseDisasterPawnHistorySlot.Adult, 0.12f,
                18f, true, 45f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <45", "", "", "建造技能在5~10之间; 制作技能在3~8之间; 建造必定单火",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 5, 10), new MouseDisasterPawnHistorySkillRange("Crafting", 3, 8) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Construction", 1f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A010", "MouseDisaster_History_A010", "鼠灾 破布缝匠",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, 55f, false,
                -25f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "", "", "制作技能在5~10之间; 艺术技能在1~4之间; 优先生成普通低品质衣物",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Crafting", 5, 10), new MouseDisasterPawnHistorySkillRange("Artistic", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A011", "MouseDisaster_History_A011", "鼠灾 病皮鞣工",
                MouseDisasterPawnHistorySlot.Adult, 0.09f,
                18f, true, 60f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "制作技能在6~11之间; 动物技能在1~4之间; 不强制携带武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Crafting", 6, 11), new MouseDisasterPawnHistorySkillRange("Animals", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A012", "MouseDisaster_History_A012", "鼠灾 草药辨者",
                MouseDisasterPawnHistorySlot.Adult, 0.11f,
                18f, true, 60f, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "种植技能在5~10之间; 医学技能在3~8之间; 医学可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 5, 10), new MouseDisasterPawnHistorySkillRange("Medicine", 3, 8) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Medicine", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A013", "MouseDisaster_History_A013", "鼠灾 熄窑守工",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 60f, false,
                10f, 50f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "制作技能在4~10之间; 建造技能在2~5之间; 对高温环境有叙事适配",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Crafting", 4, 10), new MouseDisasterPawnHistorySkillRange("Construction", 2, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A014", "MouseDisaster_History_A014", "鼠灾 断粮夜逃",
                MouseDisasterPawnHistorySlot.Adult, 0.16f,
                18f, true, float.PositiveInfinity, false,
                -30f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "种植技能在2~6之间; 近战技能在1~5之间; 更适合低饱食度事件",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 2, 6), new MouseDisasterPawnHistorySkillRange("Melee", 1, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A015", "MouseDisaster_History_A015", "鼠灾 河滩搭桥",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, 50f, false,
                -5f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <50", "", "", "建造技能在5~10之间; 制作技能在3~7之间; 建造必定单火",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 5, 10), new MouseDisasterPawnHistorySkillRange("Crafting", 3, 7) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Construction", 1f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A016", "MouseDisaster_History_A016", "鼠灾 废村搜寻",
                MouseDisasterPawnHistorySlot.Adult, 0.12f,
                18f, true, 55f, false,
                -25f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "", "", "射击技能在2~7之间; 种植技能在1~5之间; 可优先生成侦察型描述",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Shooting", 2, 7), new MouseDisasterPawnHistorySkillRange("Plants", 1, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A017", "MouseDisaster_History_A017", "鼠灾 雪路引者",
                MouseDisasterPawnHistorySlot.Adult, 0.09f,
                18f, true, 55f, false,
                -40f, 20f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "", "", "动物技能在3~8之间; 种植技能在1~4之间; 不应默认携带重型衣物",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Animals", 3, 8), new MouseDisasterPawnHistorySkillRange("Plants", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A018", "MouseDisaster_History_A018", "鼠灾 沙尘驮夫",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, 50f, false,
                5f, 50f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <50", "", "", "动物技能在5~10之间; 建造技能在1~4之间; 动物必定单火",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Animals", 5, 10), new MouseDisasterPawnHistorySkillRange("Construction", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Animals", 1f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A019", "MouseDisaster_History_A019", "鼠灾 营地守夜",
                MouseDisasterPawnHistorySlot.Adult, 0.12f,
                18f, true, 60f, false,
                -30f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "射击技能在3~8之间; 近战技能在2~6之间; 至少保留一种战斗兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Shooting", 3, 8), new MouseDisasterPawnHistorySkillRange("Melee", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[][] { new string[] { "Shooting", "Melee" } }, MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A020", "MouseDisaster_History_A020", "鼠灾 绕关失亲",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 40f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <40", "", "", "社交技能在4~9之间; 近战技能在1~5之间; 社交可能有双火",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 9), new MouseDisasterPawnHistorySkillRange("Melee", 1, 5) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Social", 0.45f, 0.35f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A021", "MouseDisaster_History_A021", "鼠灾 旧标绘路",
                MouseDisasterPawnHistorySlot.Adult, 0.09f,
                18f, true, 50f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <50", "", "", "智识技能在5~10之间; 艺术技能在2~6之间; 不要求战斗兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 5, 10), new MouseDisasterPawnHistorySkillRange("Artistic", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A022", "MouseDisaster_History_A022", "鼠灾 寻亲流亡",
                MouseDisasterPawnHistorySlot.Adult, 0.11f,
                18f, true, 60f, false,
                -25f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "社交技能在4~8之间; 动物技能在1~4之间; 可优先选择善于安抚的特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 8), new MouseDisasterPawnHistorySkillRange("Animals", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A023", "MouseDisaster_History_A023", "鼠灾 难队领路",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, 60f, false,
                -30f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "社交必定单火, 有可能双火; 社交技能在6~11之间; 种植技能在2~6之间",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 6, 11), new MouseDisasterPawnHistorySkillRange("Plants", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Social", 1f, 0.35f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A024", "MouseDisaster_History_A024", "鼠灾 破屋补匠",
                MouseDisasterPawnHistorySlot.Adult, 0.13f,
                18f, true, float.PositiveInfinity, false,
                -35f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "建造技能在5~11之间; 制作技能在3~7之间; 建造必定单火",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 5, 11), new MouseDisasterPawnHistorySkillRange("Crafting", 3, 7) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Construction", 1f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A025", "MouseDisaster_History_A025", "鼠灾 灾后掩埋",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, float.PositiveInfinity, false,
                -20f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "建造技能在2~6之间; 种植技能在1~4之间; 不强制增加精神类特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 2, 6), new MouseDisasterPawnHistorySkillRange("Plants", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A026", "MouseDisaster_History_A026", "鼠灾 讨粮说客",
                MouseDisasterPawnHistorySlot.Adult, 0.13f,
                18f, true, float.PositiveInfinity, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "社交技能在6~12之间; 社交必定单火; 不强制携带贵重物品",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 6, 12) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Social", 1f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A027", "MouseDisaster_History_A027", "鼠灾 物资换手",
                MouseDisasterPawnHistorySlot.Adult, 0.11f,
                18f, true, 55f, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "", "", "社交技能在5~10之间; 智识技能在2~6之间; 适合商队和援助事件",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 5, 10), new MouseDisasterPawnHistorySkillRange("Intellectual", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A028", "MouseDisaster_History_A028", "鼠灾 逃册抄手",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 60f, false,
                -20f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "智识技能在6~12之间; 社交技能在1~5之间; 智识可能有双火",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 6, 12), new MouseDisasterPawnHistorySkillRange("Social", 1, 5) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Intellectual", 0.45f, 0.35f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A029", "MouseDisaster_History_A029", "鼠灾 临灶分粮",
                MouseDisasterPawnHistorySlot.Adult, 0.14f,
                18f, true, float.PositiveInfinity, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "烹饪技能在6~12之间; 烹饪必定单火, 有可能双火; 种植技能在1~4之间",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Cooking", 6, 12), new MouseDisasterPawnHistorySkillRange("Plants", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Cooking", 1f, 0.35f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A030", "MouseDisaster_History_A030", "鼠灾 伤棚照料",
                MouseDisasterPawnHistorySlot.Adult, 0.11f,
                18f, true, 60f, false,
                -15f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "医学技能在4~9之间; 社交技能在2~7之间; 医学可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 4, 9), new MouseDisasterPawnHistorySkillRange("Social", 2, 7) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Medicine", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A031", "MouseDisaster_History_A031", "鼠灾 鼠蛋保育",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, 55f, false,
                0f, 40f, Gender.Female,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "", "", "社交技能在3~8之间; 医学技能在2~6之间; 可优先选择照料类特质; 不强制生成亲属关系",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 3, 8), new MouseDisasterPawnHistorySkillRange("Medicine", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A032", "MouseDisaster_History_A032", "鼠灾 夜故事者",
                MouseDisasterPawnHistorySlot.Adult, 0.09f,
                18f, true, 60f, false,
                -5f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "社交技能在4~9之间; 艺术技能在2~7之间; 不要求战斗兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 9), new MouseDisasterPawnHistorySkillRange("Artistic", 2, 7) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A033", "MouseDisaster_History_A033", "鼠灾 封村传讯",
                MouseDisasterPawnHistorySlot.Adult, 0.12f,
                18f, true, 45f, false,
                -25f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <45", "", "", "社交技能在4~9之间; 智识技能在2~6之间; 移动和搬运能力不应被严重削弱",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 9), new MouseDisasterPawnHistorySkillRange("Intellectual", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A034", "MouseDisaster_History_A034", "鼠灾 集市搬袋",
                MouseDisasterPawnHistorySlot.Adult, 0.13f,
                18f, true, 55f, false,
                -15f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "", "", "建造技能在2~7之间; 制作技能在1~4之间; 更适合低社交生成",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 2, 7), new MouseDisasterPawnHistorySkillRange("Crafting", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A035", "MouseDisaster_History_A035", "鼠灾 旧货估价",
                MouseDisasterPawnHistorySlot.Adult, 0.09f,
                18f, true, 60f, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "智识技能在4~9之间; 社交技能在3~8之间; 社交或智识至少有一项兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 4, 9), new MouseDisasterPawnHistorySkillRange("Social", 3, 8) }, new MouseDisasterPawnHistoryPassionRule[0], new string[][] { new string[] { "Social", "Intellectual" } }, MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A036", "MouseDisaster_History_A036", "鼠灾 分粮调停",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 60f, false,
                -10f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "社交必定单火, 有可能双火; 社交技能在7~12之间; 不强制增加善良特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 7, 12) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Social", 1f, 0.35f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A037", "MouseDisaster_History_A037", "鼠灾 粮票守者",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 60f, false,
                -20f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "智识技能在5~10之间; 社交技能在2~6之间; 不强制携带银钱",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 5, 10), new MouseDisasterPawnHistorySkillRange("Social", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A038", "MouseDisaster_History_A038", "鼠灾 粮仓拒守",
                MouseDisasterPawnHistorySlot.Adult, 0.11f,
                18f, true, 55f, false,
                -25f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "", "", "近战技能在5~10之间; 射击技能在2~7之间; 至少保留一种战斗兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Melee", 5, 10), new MouseDisasterPawnHistorySkillRange("Shooting", 2, 7) }, new MouseDisasterPawnHistoryPassionRule[0], new string[][] { new string[] { "Shooting", "Melee" } }, MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A039", "MouseDisaster_History_A039", "鼠灾 返乡逃兵",
                MouseDisasterPawnHistorySlot.Adult, 0.09f,
                18f, true, 45f, false,
                -30f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <45", "", "", "射击技能在4~9之间; 近战技能在4~9之间; 可优先选择畏缩或警觉类特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Shooting", 4, 9), new MouseDisasterPawnHistorySkillRange("Melee", 4, 9) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A040", "MouseDisaster_History_A040", "鼠灾 营外设陷",
                MouseDisasterPawnHistorySlot.Adult, 0.12f,
                18f, true, 55f, false,
                -20f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "", "", "建造技能在4~9之间; 动物技能在2~7之间; 制作技能在2~6之间",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 4, 9), new MouseDisasterPawnHistorySkillRange("Animals", 2, 7), new MouseDisasterPawnHistorySkillRange("Crafting", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A041", "MouseDisaster_History_A041", "鼠灾 盗粮弃徒",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 40f, false,
                -10f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <40", "", "", "近战技能在3~8之间; 社交技能在2~6之间; 不保证生成负面特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Melee", 3, 8), new MouseDisasterPawnHistorySkillRange("Social", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A042", "MouseDisaster_History_A042", "鼠灾 伤疤猎手",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, 60f, false,
                -20f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "", "", "射击技能在5~11之间; 动物技能在2~6之间; 射击可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Shooting", 5, 11), new MouseDisasterPawnHistorySkillRange("Animals", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Shooting", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A043", "MouseDisaster_History_A043", "鼠灾 驱鼠仓工",
                MouseDisasterPawnHistorySlot.Adult, 0.13f,
                18f, true, float.PositiveInfinity, false,
                -30f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "", "", "近战技能在4~9之间; 动物技能在2~5之间; 不强制携带远程武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Melee", 4, 9), new MouseDisasterPawnHistorySkillRange("Animals", 2, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A044", "MouseDisaster_History_A044", "鼠灾 疫棚搬运",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 60f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.Plague,
                ">=18, <60", "鼠疫相关事件", "", "医学技能在1~5之间; 种植技能在2~6之间; 适合附带隔离或疾病记录",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 1, 5), new MouseDisasterPawnHistorySkillRange("Plants", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A045", "MouseDisaster_History_A045", "鼠灾 隔棚看守",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 60f, false,
                -15f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.Plague,
                ">=18, <60", "鼠疫相关事件", "", "医学技能在3~8之间; 社交技能在2~6之间; 不强制带有感染状态",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 3, 8), new MouseDisasterPawnHistorySkillRange("Social", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A046", "MouseDisaster_History_A046", "鼠灾 疫后照料",
                MouseDisasterPawnHistorySlot.Adult, 0.06f,
                18f, true, float.PositiveInfinity, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.Plague,
                ">=18", "鼠疫相关事件", "", "医学技能在2~6之间; 种植技能在2~6之间; 事件接入时才考虑病史效果",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 2, 6), new MouseDisasterPawnHistorySkillRange("Plants", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A047", "MouseDisaster_History_A047", "鼠灾 伪装潜粮",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 40f, false,
                -15f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.Theft,
                ">=18, <40", "偷窃或潜入事件", "", "射击技能在2~7之间; 近战技能在2~7之间; 事件专属时才增加潜入相关效果",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Shooting", 2, 7), new MouseDisasterPawnHistorySkillRange("Melee", 2, 7) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A048", "MouseDisaster_History_A048", "鼠灾 围营掘路",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, 60f, false,
                -30f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.Siege,
                ">=18, <60", "鼠灾围攻或强势围攻", "", "建造技能在2~6之间; 近战技能在3~8之间; 适合保留一项生存类兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 2, 6), new MouseDisasterPawnHistorySkillRange("Melee", 3, 8) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A049", "MouseDisaster_History_A049", "鼠灾 破仓救饥",
                MouseDisasterPawnHistorySlot.Adult, 0.09f,
                18f, true, 45f, false,
                -20f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <45", "", "", "建造技能在5~10之间; 近战技能在4~8之间; 建造或近战至少有一项兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 5, 10), new MouseDisasterPawnHistorySkillRange("Melee", 4, 8) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y001", "MouseDisaster_History_Y001", "鼠灾 废墟幼崽",
                MouseDisasterPawnHistorySlot.Young, 0.16f,
                float.NegativeInfinity, false, 7f, false,
                -15f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                "<7", "", "鼠灾 废村搜寻 / 鼠灾 破屋补匠", "不添加成人技能; 儿童阶段可给制作或智识0~2; 不生成武器",
                new MouseDisasterPawnHistorySkillRange[0], new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None | MouseDisasterPawnHistoryRestriction.NoWeapons),
            new MouseDisasterPawnHistoryDefinition(
                "Y002", "MouseDisaster_History_Y002", "鼠灾 失田幼崽",
                MouseDisasterPawnHistorySlot.Young, 0.14f,
                float.NegativeInfinity, false, 7f, false,
                -20f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                "<7", "", "鼠灾 旱田守望 / 鼠灾 废田拾穗", "种植技能0~3; 动物技能0~2; 不强制增加特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 0, 3), new MouseDisasterPawnHistorySkillRange("Animals", 0, 2) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y003", "MouseDisaster_History_Y003", "鼠灾 洞隙信童",
                MouseDisasterPawnHistorySlot.Young, 0.12f,
                7f, false, 18f, false,
                -25f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 封村传讯 / 鼠灾 旧标绘路", "社交技能在2~6之间; 动物技能在1~3之间; 社交可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 2, 6), new MouseDisasterPawnHistorySkillRange("Animals", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Social", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y004", "MouseDisaster_History_Y004", "鼠灾 粮坊筛徒",
                MouseDisasterPawnHistorySlot.Young, 0.13f,
                7f, false, 18f, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 霉粮筛手 / 鼠灾 临灶分粮", "烹饪技能在1~5之间; 种植技能在1~4之间; 不强制保留母女关系",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Cooking", 1, 5), new MouseDisasterPawnHistorySkillRange("Plants", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y005", "MouseDisaster_History_Y005", "鼠灾 护蛋学徒",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                7f, false, 18f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 伤棚照料 / 鼠灾 鼠蛋保育", "社交技能在2~6之间; 医学技能在1~4之间; 可优先选择照料类特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 2, 6), new MouseDisasterPawnHistorySkillRange("Medicine", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y006", "MouseDisaster_History_Y006", "鼠灾 认路孤童",
                MouseDisasterPawnHistorySlot.Young, 0.12f,
                7f, false, 18f, false,
                -30f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 旧标绘路 / 鼠灾 难队领路", "智识技能在2~6之间; 种植技能在1~4之间; 不生成重型装备",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 2, 6), new MouseDisasterPawnHistorySkillRange("Plants", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y007", "MouseDisaster_History_Y007", "鼠灾 看畜学徒",
                MouseDisasterPawnHistorySlot.Young, 0.11f,
                7f, false, 18f, false,
                -15f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 灾年牧鼠 / 鼠灾 沙尘驮夫", "动物技能在3~7之间; 动物必定单火; 不强制携带武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Animals", 3, 7) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Animals", 1f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y008", "MouseDisaster_History_Y008", "鼠灾 磨坊孤徒",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                7f, false, 18f, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 石磨孤徒 / 鼠灾 临灶分粮", "制作技能在2~6之间; 烹饪技能在1~4之间; 可保留制作兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Crafting", 2, 6), new MouseDisasterPawnHistorySkillRange("Cooking", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y009", "MouseDisaster_History_Y009", "鼠灾 营火听童",
                MouseDisasterPawnHistorySlot.Young, 0.13f,
                4f, false, 12f, false,
                -5f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">4, <12", "", "鼠灾 夜故事者 / 鼠灾 分粮调停", "社交技能在1~4之间; 艺术技能在1~4之间; 不强制增加悲观类特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 1, 4), new MouseDisasterPawnHistorySkillRange("Artistic", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y010", "MouseDisaster_History_Y010", "鼠灾 隔棚幼童",
                MouseDisasterPawnHistorySlot.Young, 0.08f,
                7f, false, 18f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.Plague,
                ">7, <18", "鼠疫相关事件", "鼠灾 疫棚搬运 / 鼠灾 隔棚看守", "医学技能在1~4之间; 智识技能在1~4之间; 事件接入时才考虑病史效果",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 1, 4), new MouseDisasterPawnHistorySkillRange("Intellectual", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y011", "MouseDisaster_History_Y011", "鼠灾 废屋孤童",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                7f, false, 18f, false,
                -25f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 寻亲流亡 / 鼠灾 断粮夜逃", "种植技能在1~5之间; 动物技能在1~4之间; 不强制生成亲属关系",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 1, 5), new MouseDisasterPawnHistorySkillRange("Animals", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y012", "MouseDisaster_History_Y012", "鼠灾 守夜学徒",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                -30f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.Conflict,
                ">7, <18", "围攻或偷袭事件", "鼠灾 营地守夜 / 鼠灾 粮仓拒守", "射击技能在1~4之间; 近战技能在1~4之间; 儿童阶段不生成重型武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Shooting", 1, 4), new MouseDisasterPawnHistorySkillRange("Melee", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A050", "MouseDisaster_History_A050", "鼠灾 护弟长姐",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, float.PositiveInfinity, false,
                -25f, 40f, Gender.Female,
                new string[] { "O-002" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "O-002 鼠蛋遗弃", "", "社交技能在4~9之间; 医学技能在2~6之间; 可优先选择照料类特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 9), new MouseDisasterPawnHistorySkillRange("Medicine", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A051", "MouseDisaster_History_A051", "鼠灾 托孤病母",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 55f, false,
                -20f, 40f, Gender.Female,
                new string[] { "O-003", "N-033" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "O-003 耗子分妈 / N-033 鼠疫托孤", "", "医学技能在3~8之间; 社交技能在4~9之间; 只在母亲角色中固定为 female",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 3, 8), new MouseDisasterPawnHistorySkillRange("Social", 4, 9) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A052", "MouseDisaster_History_A052", "鼠灾 讨粮鼠母",
                MouseDisasterPawnHistorySlot.Adult, 0.09f,
                18f, true, 60f, false,
                -15f, 40f, Gender.Female,
                new string[] { "O-004", "N-015" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "O-004 乞讨的灾荒鼠妈 / N-015 难民接济（婴儿）", "", "社交技能在4~9之间; 医学技能在2~6之间; 优先考虑善良或照料类候选",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 9), new MouseDisasterPawnHistorySkillRange("Medicine", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A053", "MouseDisaster_History_A053", "鼠灾 为家盗粮",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 55f, false,
                -15f, 45f, Gender.None,
                new string[] { "O-006", "O-007", "N-039" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "O-006 偷窃的鼠族 / O-007 偷窃的鼠蛋 / N-039 鼠疫偷窃", "", "近战技能在2~7之间; 社交技能在1~5之间; 不保证生成负面特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Melee", 2, 7), new MouseDisasterPawnHistorySkillRange("Social", 1, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A054", "MouseDisaster_History_A054", "鼠灾 荒地求生",
                MouseDisasterPawnHistorySlot.Adult, 0.11f,
                18f, true, float.PositiveInfinity, false,
                -30f, 45f, Gender.None,
                new string[] { "O-008", "O-010", "N-027" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "O-008 游荡的野生鼠族 / O-010 游荡的野生鼠群 / N-027 鼠灾路过", "", "动物技能在2~7之间; 射击技能在1~5之间; 适合低装备和野外生成",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Animals", 2, 7), new MouseDisasterPawnHistorySkillRange("Shooting", 1, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A055", "MouseDisaster_History_A055", "鼠灾 难营管事",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, 60f, false,
                -25f, 45f, Gender.None,
                new string[] { "O-001", "O-011" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "O-001 大型流民冲击 / O-011 灾荒逃难者", "", "社交技能在3~8之间; 建造技能在2~6之间; 不强制携带贵重物品",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 3, 8), new MouseDisasterPawnHistorySkillRange("Construction", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A056", "MouseDisaster_History_A056", "鼠灾 囚笼看守",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 60f, false,
                -20f, 45f, Gender.None,
                new string[] { "O-012", "N-034" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "O-012 流民商队 / N-034 鼠疫商队", "", "社交技能在4~9之间; 动物技能在2~6之间; 不强制生成敌对特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 9), new MouseDisasterPawnHistorySkillRange("Animals", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A057", "MouseDisaster_History_A057", "鼠灾 鼠蛋商人",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 60f, false,
                -15f, 45f, Gender.None,
                new string[] { "O-013" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "O-013 易子而食", "", "社交技能在5~10之间; 智识技能在2~6之间; 事件专属时才考虑交易相关状态",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 5, 10), new MouseDisasterPawnHistorySkillRange("Intellectual", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A058", "MouseDisaster_History_A058", "鼠灾 城外乞食",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, float.PositiveInfinity, false,
                -25f, 45f, Gender.None,
                new string[] { "O-014", "N-026" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "O-014 鼠灾围攻 / N-026 强势围攻", "", "社交技能在3~8之间; 近战技能在2~6之间; 不默认视为主动敌对",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 3, 8), new MouseDisasterPawnHistorySkillRange("Melee", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A059", "MouseDisaster_History_A059", "鼠灾 接济厨子",
                MouseDisasterPawnHistorySlot.Adult, 0.12f,
                18f, true, 60f, false,
                -10f, 40f, Gender.None,
                new string[] { "N-011", "N-012" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-011/N-012 难民接济（食物）", "", "烹饪技能在6~11之间; 种植技能在1~4之间; 烹饪必定单火, 有可能双火",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Cooking", 6, 11), new MouseDisasterPawnHistorySkillRange("Plants", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Cooking", 1f, 0.35f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A060", "MouseDisaster_History_A060", "鼠灾 难队药师",
                MouseDisasterPawnHistorySlot.Adult, 0.09f,
                18f, true, 60f, false,
                -20f, 40f, Gender.None,
                new string[] { "N-013", "N-036" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-013 难民接济（药品） / N-036 鼠疫流亡者", "", "医学技能在5~10之间; 种植技能在2~6之间; 医学可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 5, 10), new MouseDisasterPawnHistorySkillRange("Plants", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Medicine", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A061", "MouseDisaster_History_A061", "鼠灾 白银交易",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 60f, false,
                -20f, 40f, Gender.None,
                new string[] { "N-014", "N-024" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-014 难民接济（白银） / N-024 情报交易（小居住点-白银）", "", "社交技能在4~8之间; 智识技能在3~7之间; 不强制携带白银",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 8), new MouseDisasterPawnHistorySkillRange("Intellectual", 3, 7) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A062", "MouseDisaster_History_A062", "鼠灾 残图情报",
                MouseDisasterPawnHistorySlot.Adult, 0.06f,
                18f, true, 60f, false,
                -20f, 45f, Gender.None,
                new string[] { "N-016", "N-017", "N-018" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-016/N-017/N-018 情报交易（宝藏）", "", "智识技能在5~10之间; 社交技能在3~8之间; 交付奖励和地图地点由事件实际结算",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 5, 10), new MouseDisasterPawnHistorySkillRange("Social", 3, 8) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A063", "MouseDisaster_History_A063", "鼠灾 废墟情报",
                MouseDisasterPawnHistorySlot.Adult, 0.06f,
                18f, true, 60f, false,
                -25f, 45f, Gender.None,
                new string[] { "N-019", "N-020", "N-021" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-019/N-020/N-021 情报交易（建筑群）", "", "建造技能在3~8之间; 智识技能在4~9之间; 不将情报地点直接视为已经探索",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 3, 8), new MouseDisasterPawnHistorySkillRange("Intellectual", 4, 9) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A064", "MouseDisaster_History_A064", "鼠灾 小寨记事",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 60f, false,
                -20f, 40f, Gender.None,
                new string[] { "N-022", "N-023", "N-024" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-022/N-023/N-024 情报交易（小居住点）", "", "社交技能在4~9之间; 智识技能在3~7之间; 社交可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 9), new MouseDisasterPawnHistorySkillRange("Intellectual", 3, 7) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Social", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A065", "MouseDisaster_History_A065", "鼠灾 待产流民",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 45f, false,
                -15f, 40f, Gender.Female,
                new string[] { "N-025", "N-040" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <45", "N-025 待产流民 / N-040 鼠疫待产流民", "", "医学技能在2~7之间; 社交技能在3~8之间; 只有事件专属生成时才绑定怀孕或生产状态",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 2, 7), new MouseDisasterPawnHistorySkillRange("Social", 3, 8) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A066", "MouseDisaster_History_A066", "鼠灾 误投搬运",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 55f, false,
                -25f, 45f, Gender.None,
                new string[] { "N-028", "N-042" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "N-028 空投失误 / N-042 鼠疫空投失误", "", "建造技能在2~6之间; 社交技能在2~7之间; 不保证携带完整空投物资",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 2, 6), new MouseDisasterPawnHistorySkillRange("Social", 2, 7) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A067", "MouseDisaster_History_A067", "鼠灾 认亲错影",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 60f, false,
                -20f, 40f, Gender.None,
                new string[] { "N-029", "N-043" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-029 错误认亲 / N-043 鼠疫错误认亲", "", "社交技能在4~9之间; 医学技能在1~5之间; 关系修正和去留由事件实际结果决定",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 9), new MouseDisasterPawnHistorySkillRange("Medicine", 1, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A068", "MouseDisaster_History_A068", "鼠灾 荒年农户",
                MouseDisasterPawnHistorySlot.Adult, 0.10f,
                18f, true, float.PositiveInfinity, false,
                -30f, 45f, Gender.None,
                new string[] { "N-030", "N-044" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18", "N-030 大荒年 / N-044 鼠疫大荒年", "", "种植技能在3~8之间; 社交技能在2~6之间; 更适合低饱食度和大规模灾荒事件",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 3, 8), new MouseDisasterPawnHistorySkillRange("Social", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A069", "MouseDisaster_History_A069", "鼠灾 遇袭护运",
                MouseDisasterPawnHistorySlot.Adult, 0.08f,
                18f, true, 60f, false,
                -25f, 45f, Gender.None,
                new string[] { "N-031", "N-046" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-031 流民抢夺商队 / N-046 鼠疫流民抢夺商队", "", "近战技能在3~8之间; 动物技能在2~6之间; 不自动继承商队货物或敌对关系",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Melee", 3, 8), new MouseDisasterPawnHistorySkillRange("Animals", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A070", "MouseDisaster_History_A070", "鼠灾 疫区流亡",
                MouseDisasterPawnHistorySlot.Adult, 0.06f,
                18f, true, 60f, false,
                -25f, 40f, Gender.None,
                new string[] { "N-032", "N-035" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-032 鼠疫游荡 / N-035 鼠疫逃难者", "", "医学技能在2~7之间; 动物技能在1~4之间; 感染状态只由事件专属逻辑决定",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 2, 7), new MouseDisasterPawnHistorySkillRange("Animals", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A071", "MouseDisaster_History_A071", "鼠灾 检棚守门",
                MouseDisasterPawnHistorySlot.Adult, 0.06f,
                18f, true, 60f, false,
                -20f, 40f, Gender.None,
                new string[] { "N-033", "N-036", "N-037" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-033 鼠疫托孤 / N-036 鼠疫流亡者 / N-037 鼠疫孤儿", "", "医学技能在3~8之间; 社交技能在2~7之间; 不强制生成感染状态",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 3, 8), new MouseDisasterPawnHistorySkillRange("Social", 2, 7) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A072", "MouseDisaster_History_A072", "鼠灾 疫营掘路",
                MouseDisasterPawnHistorySlot.Adult, 0.07f,
                18f, true, 60f, false,
                -30f, 45f, Gender.None,
                new string[] { "N-038", "N-041", "N-044" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-038 鼠疫流民 / N-041 鼠疫强势围攻 / N-044 鼠疫大荒年", "", "建造技能在3~8之间; 近战技能在2~7之间; 事件接入时才考虑隔离和围攻状态",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 3, 8), new MouseDisasterPawnHistorySkillRange("Melee", 2, 7) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A073", "MouseDisaster_History_A073", "鼠灾 疫信逃使",
                MouseDisasterPawnHistorySlot.Adult, 0.06f,
                18f, true, 55f, false,
                -25f, 45f, Gender.None,
                new string[] { "N-045" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <55", "N-045 鼠疫报复", "", "社交技能在4~9之间; 智识技能在2~6之间; 不凭经历本身判定事件幕后主使",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 4, 9), new MouseDisasterPawnHistorySkillRange("Intellectual", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "A074", "MouseDisaster_History_A074", "鼠灾 撤营向导",
                MouseDisasterPawnHistorySlot.Adult, 0.06f,
                18f, true, 60f, false,
                -30f, 45f, Gender.None,
                new string[] { "N-047" }, MouseDisasterPawnHistoryEventCategory.None,
                ">=18, <60", "N-047 鼠难民屠杀", "", "建造技能在3~8之间; 近战技能在2~7之间; 社交技能在2~6之间; 任务结算不自动替换为复仇特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 3, 8), new MouseDisasterPawnHistorySkillRange("Melee", 2, 7), new MouseDisasterPawnHistorySkillRange("Social", 2, 6) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y013", "MouseDisaster_History_Y013", "鼠灾 人潮幼童",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                4f, false, 12f, false,
                -25f, 45f, Gender.None,
                new string[] { "O-001", "O-011" }, MouseDisasterPawnHistoryEventCategory.None,
                ">4, <12", "O-001 大型流民冲击 / O-011 灾荒逃难者", "鼠灾 寻亲流亡 / 鼠灾 难队领路", "社交技能在1~4之间; 不自动生成亲属关系; 可保留对人群和路线的记忆",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y014", "MouseDisaster_History_Y014", "鼠灾 弃屋鼠蛋",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                float.NegativeInfinity, false, 4f, false,
                -20f, 40f, Gender.None,
                new string[] { "O-002", "N-033", "N-037" }, MouseDisasterPawnHistoryEventCategory.None,
                "<4", "O-002 鼠蛋遗弃 / N-033 鼠疫托孤 / N-037 鼠疫孤儿", "鼠灾 断粮夜逃 / 鼠灾 寻亲流亡", "不添加成人技能; 婴儿阶段不生成武器; 事件接入时才追踪母亲是否存活",
                new MouseDisasterPawnHistorySkillRange[0], new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None | MouseDisasterPawnHistoryRestriction.NoWeapons),
            new MouseDisasterPawnHistoryDefinition(
                "Y015", "MouseDisaster_History_Y015", "鼠灾 门前托蛋",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                float.NegativeInfinity, false, 4f, false,
                -20f, 40f, Gender.None,
                new string[] { "O-003", "N-015", "N-033" }, MouseDisasterPawnHistoryEventCategory.None,
                "<4", "O-003 耗子分妈 / N-015 难民接济（婴儿） / N-033 鼠疫托孤", "鼠灾 鼠蛋保育 / 鼠灾 托孤病母", "不添加成人技能; 不强制生成母子关系; 事件接入时才考虑观音土或病程效果",
                new MouseDisasterPawnHistorySkillRange[0], new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y016", "MouseDisaster_History_Y016", "鼠灾 分粮学徒",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                -20f, 40f, Gender.None,
                new string[] { "O-004", "O-005", "N-011", "N-012" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "O-004 乞讨的灾荒鼠妈 / O-005 乞讨的鼠族队伍 / N-011/N-012 难民接济（食物）", "鼠灾 讨粮说客 / 鼠灾 分粮调停", "社交技能在2~6之间; 智识技能在1~3之间; 不把短期分粮记录变成永久关系",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 2, 6), new MouseDisasterPawnHistorySkillRange("Intellectual", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y017", "MouseDisaster_History_Y017", "鼠灾 仓桶藏童",
                MouseDisasterPawnHistorySlot.Young, 0.08f,
                7f, false, 18f, false,
                -15f, 45f, Gender.None,
                new string[] { "O-006", "O-007", "N-039" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "O-006 偷窃的鼠族 / O-007 偷窃的鼠蛋 / N-039 鼠疫偷窃", "鼠灾 伪装潜粮 / 鼠灾 为家盗粮", "近战技能在1~4之间; 射击技能在0~3之间; 不保证生成负面特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Melee", 1, 4), new MouseDisasterPawnHistorySkillRange("Shooting", 0, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y018", "MouseDisaster_History_Y018", "鼠灾 荒洞幼崽",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                float.NegativeInfinity, false, 7f, false,
                -30f, 45f, Gender.None,
                new string[] { "O-009", "O-010", "N-027" }, MouseDisasterPawnHistoryEventCategory.None,
                "<7", "O-009 游荡的野生鼠蛋 / O-010 游荡的野生鼠群 / N-027 鼠灾路过", "鼠灾 荒地求生 / 鼠灾 废村搜寻", "不添加成人技能; 动物技能0~3; 不生成武器; 事件接入时才决定是否可被驯服",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Animals", 0, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None | MouseDisasterPawnHistoryRestriction.NoWeapons),
            new MouseDisasterPawnHistoryDefinition(
                "Y019", "MouseDisaster_History_Y019", "鼠灾 笼旁幼童",
                MouseDisasterPawnHistorySlot.Young, 0.08f,
                7f, false, 18f, false,
                -20f, 45f, Gender.None,
                new string[] { "O-012", "N-034" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "O-012 流民商队 / N-034 鼠疫商队", "鼠灾 沙尘驮夫 / 鼠灾 囚笼看守", "社交技能在2~5之间; 动物技能在1~4之间; 不自动继承商队货物",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 2, 5), new MouseDisasterPawnHistorySkillRange("Animals", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y020", "MouseDisaster_History_Y020", "鼠灾 交易藏童",
                MouseDisasterPawnHistorySlot.Young, 0.08f,
                7f, false, 18f, false,
                -15f, 40f, Gender.None,
                new string[] { "O-013", "N-015" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "O-013 易子而食 / N-015 难民接济（婴儿）", "鼠灾 鼠蛋保育 / 鼠灾 鼠蛋商人", "社交技能在1~5之间; 不强制生成交易记忆以外的负面特质; 关系结果由事件实际分支决定",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 1, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y021", "MouseDisaster_History_Y021", "鼠灾 围营水童",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                -25f, 45f, Gender.None,
                new string[] { "O-014", "N-026", "N-041" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "O-014 鼠灾围攻 / N-026 强势围攻 / N-041 鼠疫强势围攻", "鼠灾 城外乞食 / 鼠灾 营地守夜", "近战技能在1~4之间; 社交技能在1~4之间; 儿童阶段不生成重型武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Melee", 1, 4), new MouseDisasterPawnHistorySkillRange("Social", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y022", "MouseDisaster_History_Y022", "鼠灾 接济记童",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                -20f, 40f, Gender.None,
                new string[] { "N-011", "N-012", "N-013", "N-014", "N-015" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "N-011/N-012/N-013/N-014/N-015 难民接济", "鼠灾 接济厨子 / 鼠灾 难队药师", "烹饪技能在1~4之间; 医学技能在1~3之间; 智识技能在1~3之间; 不强制生成物资",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Cooking", 1, 4), new MouseDisasterPawnHistorySkillRange("Medicine", 1, 3), new MouseDisasterPawnHistorySkillRange("Intellectual", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y023", "MouseDisaster_History_Y023", "鼠灾 地图迷童",
                MouseDisasterPawnHistorySlot.Young, 0.08f,
                7f, false, 18f, false,
                -25f, 45f, Gender.None,
                new string[] { "N-016", "N-017", "N-018", "N-019", "N-020", "N-021", "N-022", "N-023", "N-024" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "N-016~N-024 情报交易", "鼠灾 残图情报 / 鼠灾 旧标绘路", "智识技能在2~5之间; 种植技能在1~3之间; 不把地图标记视为已探索地点",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 2, 5), new MouseDisasterPawnHistorySkillRange("Plants", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y024", "MouseDisaster_History_Y024", "鼠灾 产队幼童",
                MouseDisasterPawnHistorySlot.Young, 0.07f,
                7f, false, 18f, false,
                -15f, 40f, Gender.None,
                new string[] { "N-025", "N-040" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "N-025 待产流民 / N-040 鼠疫待产流民", "鼠灾 待产流民 / 鼠灾 鼠蛋保育", "社交技能在2~5之间; 医学技能在1~3之间; 不自动生成新生儿或亲属关系",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 2, 5), new MouseDisasterPawnHistorySkillRange("Medicine", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y025", "MouseDisaster_History_Y025", "鼠灾 错投幼童",
                MouseDisasterPawnHistorySlot.Young, 0.07f,
                float.NegativeInfinity, false, 7f, false,
                -25f, 45f, Gender.None,
                new string[] { "N-028", "N-042" }, MouseDisasterPawnHistoryEventCategory.None,
                "<7", "N-028 空投失误 / N-042 鼠疫空投失误", "鼠灾 误投搬运 / 鼠灾 废村搜寻", "不添加成人技能; 制作技能0~2; 不生成空投物资; 事件接入时才决定是否有照料者",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Crafting", 0, 2) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y026", "MouseDisaster_History_Y026", "鼠灾 错名幼童",
                MouseDisasterPawnHistorySlot.Young, 0.08f,
                7f, false, 18f, false,
                -20f, 40f, Gender.None,
                new string[] { "N-029", "N-043" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "N-029 错误认亲 / N-043 鼠疫错误认亲", "鼠灾 认亲错影 / 鼠灾 寻亲流亡", "社交技能在1~5之间; 不强制改名; 关系与身份结果由事件实际状态决定",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 1, 5) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y027", "MouseDisaster_History_Y027", "鼠灾 荒年营童",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                7f, false, 18f, false,
                -30f, 45f, Gender.None,
                new string[] { "N-030", "N-044" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "N-030 大荒年 / N-044 鼠疫大荒年", "鼠灾 荒年农户 / 鼠灾 断粮夜逃", "种植技能在1~4之间; 社交技能在1~4之间; 不强制增加悲观类特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 1, 4), new MouseDisasterPawnHistorySkillRange("Social", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y028", "MouseDisaster_History_Y028", "鼠灾 疫区幼童",
                MouseDisasterPawnHistorySlot.Young, 0.08f,
                7f, false, 18f, false,
                -25f, 40f, Gender.None,
                new string[] { "N-032", "N-035", "N-037" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "N-032 鼠疫游荡 / N-035 鼠疫逃难者 / N-037 鼠疫孤儿", "鼠灾 疫区流亡 / 鼠灾 检棚守门", "医学技能在1~4之间; 智识技能在1~3之间; 感染和隔离状态只由事件专属逻辑决定",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 1, 4), new MouseDisasterPawnHistorySkillRange("Intellectual", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y029", "MouseDisaster_History_Y029", "鼠灾 木屋遗童",
                MouseDisasterPawnHistorySlot.Young, 0.07f,
                7f, false, 18f, false,
                -30f, 45f, Gender.None,
                new string[] { "N-047" }, MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "N-047 鼠难民屠杀", "鼠灾 撤营向导 / 鼠灾 营地守夜", "建造技能在1~4之间; 社交技能在1~4之间; 不自动生成营地亲属关系; 儿童阶段不生成重型武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 1, 4), new MouseDisasterPawnHistorySkillRange("Social", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y030", "MouseDisaster_History_Y030", "鼠灾 旱地学徒",
                MouseDisasterPawnHistorySlot.Young, 0.12f,
                4f, false, 12f, false,
                5f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">4, <12", "", "鼠灾 旱田守望 / 鼠灾 废田拾穗", "种植技能在1~4之间; 不添加成人阶段技能; 可优先保留对农活的兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y031", "MouseDisaster_History_Y031", "鼠灾 分种学徒",
                MouseDisasterPawnHistorySlot.Young, 0.11f,
                7f, false, 18f, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 废田拾穗 / 鼠灾 草药辨者", "种植技能在2~5之间; 智识技能在1~3之间; 种植可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 2, 5), new MouseDisasterPawnHistorySkillRange("Intellectual", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Plants", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y032", "MouseDisaster_History_Y032", "鼠灾 围栏牧童",
                MouseDisasterPawnHistorySlot.Young, 0.11f,
                7f, false, 18f, false,
                -15f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 灾年牧鼠 / 鼠灾 沙尘驮夫", "动物技能在3~7之间; 动物必定单火; 不强制携带武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Animals", 3, 7) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Animals", 1f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y033", "MouseDisaster_History_Y033", "鼠灾 枯井水童",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                7f, false, 18f, false,
                -5f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 旱井挑水 / 鼠灾 封村传讯", "种植技能在1~4之间; 社交技能在1~4之间; 不让年龄过小的 Pawn 获得成人工作资格",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 1, 4), new MouseDisasterPawnHistorySkillRange("Social", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y034", "MouseDisaster_History_Y034", "鼠灾 粮袋记童",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                -20f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 谷仓旧账 / 鼠灾 粮票守者", "智识技能在2~5之间; 社交技能在1~3之间; 不强制生成贵重物品",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 2, 5), new MouseDisasterPawnHistorySkillRange("Social", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y035", "MouseDisaster_History_Y035", "鼠灾 粮坊帮童",
                MouseDisasterPawnHistorySlot.Young, 0.11f,
                7f, false, 18f, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 霉粮筛手 / 鼠灾 临灶分粮", "烹饪技能在1~5之间; 种植技能在1~4之间; 不强制保留母女关系",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Cooking", 1, 5), new MouseDisasterPawnHistorySkillRange("Plants", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y036", "MouseDisaster_History_Y036", "鼠灾 补轮学徒",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                7f, false, 18f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 修仓木匠 / 鼠灾 河滩搭桥", "建造技能在2~6之间; 制作技能在1~4之间; 建造可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 2, 6), new MouseDisasterPawnHistorySkillRange("Crafting", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Construction", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y037", "MouseDisaster_History_Y037", "鼠灾 穿针学徒",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                -25f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 破布缝匠 / 鼠灾 旧货估价", "制作技能在2~6之间; 艺术技能在1~3之间; 不生成战斗装备",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Crafting", 2, 6), new MouseDisasterPawnHistorySkillRange("Artistic", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None | MouseDisasterPawnHistoryRestriction.NoWeapons),
            new MouseDisasterPawnHistoryDefinition(
                "Y038", "MouseDisaster_History_Y038", "鼠灾 猎场跟班",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                7f, false, 18f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 病皮鞣工 / 鼠灾 伤疤猎手", "动物技能在2~6之间; 射击技能在1~4之间; 不强制携带远程武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Animals", 2, 6), new MouseDisasterPawnHistorySkillRange("Shooting", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y039", "MouseDisaster_History_Y039", "鼠灾 草篮学徒",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                7f, false, 18f, false,
                -10f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 草药辨者 / 鼠灾 伤棚照料", "医学技能在1~4之间; 种植技能在1~4之间; 事件接入时才考虑病史效果",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Medicine", 1, 4), new MouseDisasterPawnHistorySkillRange("Plants", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y040", "MouseDisaster_History_Y040", "鼠灾 窑边童工",
                MouseDisasterPawnHistorySlot.Young, 0.07f,
                7f, false, 18f, false,
                10f, 50f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 熄窑守工 / 鼠灾 石磨孤徒", "制作技能在1~4之间; 建造技能在0~3之间; 不让幼年经历直接生成成人工作资格",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Crafting", 1, 4), new MouseDisasterPawnHistorySkillRange("Construction", 0, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y041", "MouseDisaster_History_Y041", "鼠灾 营火孤童",
                MouseDisasterPawnHistorySlot.Young, 0.12f,
                7f, false, 18f, false,
                -30f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 断粮夜逃 / 鼠灾 营地守夜", "社交技能在1~4之间; 近战技能在1~3之间; 不强制生成亲属关系",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 1, 4), new MouseDisasterPawnHistorySkillRange("Melee", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y042", "MouseDisaster_History_Y042", "鼠灾 河筏学徒",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                -5f, 35f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 河滩搭桥 / 鼠灾 破屋补匠", "建造技能在1~5之间; 制作技能在1~3之间; 建造可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Construction", 1, 5), new MouseDisasterPawnHistorySkillRange("Crafting", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Construction", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y043", "MouseDisaster_History_Y043", "鼠灾 劫村幼童",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                -25f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 废村搜寻 / 鼠灾 寻亲流亡", "种植技能在1~4之间; 社交技能在1~3之间; 不强制增加悲观类特质",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Plants", 1, 4), new MouseDisasterPawnHistorySkillRange("Social", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y044", "MouseDisaster_History_Y044", "鼠灾 雪印学徒",
                MouseDisasterPawnHistorySlot.Young, 0.08f,
                7f, false, 18f, false,
                -40f, 20f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 雪路引者 / 鼠灾 旧标绘路", "智识技能在1~4之间; 动物技能在1~3之间; 不生成重型装备",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Intellectual", 1, 4), new MouseDisasterPawnHistorySkillRange("Animals", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y045", "MouseDisaster_History_Y045", "鼠灾 驮兽学徒",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                5f, 50f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 沙尘驮夫 / 鼠灾 灾年牧鼠", "动物技能在3~7之间; 动物必定单火; 不强制携带武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Animals", 3, 7) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Animals", 1f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y046", "MouseDisaster_History_Y046", "鼠灾 夜警学徒",
                MouseDisasterPawnHistorySlot.Young, 0.10f,
                7f, false, 18f, false,
                -30f, 45f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.Conflict,
                ">7, <18", "围攻或偷袭事件", "鼠灾 营地守夜 / 鼠灾 粮仓拒守", "射击技能在1~4之间; 近战技能在1~4之间; 儿童阶段不生成重型武器",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Shooting", 1, 4), new MouseDisasterPawnHistorySkillRange("Melee", 1, 4) }, new MouseDisasterPawnHistoryPassionRule[0], new string[0][], MouseDisasterPawnHistoryRestriction.None),
            new MouseDisasterPawnHistoryDefinition(
                "Y047", "MouseDisaster_History_Y047", "鼠灾 绕关学徒",
                MouseDisasterPawnHistorySlot.Young, 0.09f,
                7f, false, 18f, false,
                -20f, 40f, Gender.None,
                new string[0], MouseDisasterPawnHistoryEventCategory.None,
                ">7, <18", "", "鼠灾 绕关失亲 / 鼠灾 封村传讯", "社交技能在2~6之间; 智识技能在1~3之间; 社交可能有兴趣",
                new MouseDisasterPawnHistorySkillRange[] { new MouseDisasterPawnHistorySkillRange("Social", 2, 6), new MouseDisasterPawnHistorySkillRange("Intellectual", 1, 3) }, new MouseDisasterPawnHistoryPassionRule[] { new MouseDisasterPawnHistoryPassionRule("Social", 0.45f, 0f) }, new string[0][], MouseDisasterPawnHistoryRestriction.None),
        };
    }
}
